# My basic CI/CD pipeline to automatically build and deploy the web-application to Firebase Hosting
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- checkout: self
  displayName: 'Checkout Code'

- task: NodeTool@0
  inputs:
    versionSpec: '16.x'
  displayName: 'Install Node.js'


- script: |
    npm install -g firebase-tools
    firebase deploy --only hosting --token $(FIREBASE_TOKEN) --non-interactive --project ccse-2152233
  displayName: 'Deploy to Firebase'
